### ISSUE TITLE
installation: conda install hangs

### ISSUE THREAD

**Issue by efiop** [conda-forge/dvc-feedstock#191]
From https://github.com/iterative/dvc/issues/5625#issue-831656518

> I'm unable to install dvc via conda across several systems. I think I can reproduce the issue in a Docker container so either its something very simple I'm doing wrong or its something wrong with the conda package:
> 
> ```
> docker run -it continuumio/miniconda:4.7.12
> ```
> then run 
> ```
> conda create -y -n test python=3.8 \
> && conda activate test \
> && conda install -c conda-forge dvc
> ```
> 
> This gives:
> ```
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: \ 
> ```
> and it just hangs there for at least 30min. 
>

**Comment by efiop** [comment]
It did resolve the dependencies after like an hour on my machine and has installed dvc. Need to take a closer look.

**Comment by maresb** [comment]
I managed to greet an old friend and (presumably) solve this issue.

You may want to amend the DVC docs. I'll open an issue on the main repo...

**Comment by maresb** [comment]
I think we can close this, right?

**Comment by efiop** [comment]
@maresb Thank you! :pray:
