### ISSUE TITLE
Incoming python311 migration may block on omegaconf

### ISSUE THREAD

**Issue by maresb** [conda-forge/dvc-feedstock#308]
### Comment:

 This feedstock has omegaconf as a dependency, and is also awaiting the python311 migration. Omegaconf has just been converted to noarch, but the latest version v2.2.3 is not yet compatible with Python 3.11. Support will be added in v2.2.4. Therefore, if the migrator opens the "Rebuild for python311" PR before the release of omegaconf v2.2.4, the build [will fail](https://github.com/conda-forge/omegaconf-feedstock/pull/40#issuecomment-1294669062).

**Comment by weiji14** [comment]
Closing as omegaconf=2.3.0 has been released at https://github.com/conda-forge/omegaconf-feedstock/pull/45 which supports Python 3.11.
