### ISSUE TITLE
voluptuous not in recipe

### ISSUE THREAD

**Issue by majidaldo** [conda-forge/dvc-feedstock#52]
...while it's in setup.py. this makes `dvc pull` not work when installed from conda-forge.

**Comment by efiop** [comment]
Fixed by 2bb5aea . Thank you so much for reporting! 🙂

**Comment by majidaldo** [comment]
thanks . DRY ;)

**Comment by efiop** [comment]
@majidaldo FYI: We are also introduing additional sanity checks in https://github.com/conda-forge/dvc-feedstock/pull/53 , so this doesn't happen in the future. Thanks again for the feedback, we really appreciate it! 🙂
